version: '3.4'

services:
  pong-server:
    image: node:18-alpine
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
    working_dir: /app
    environment:
      JWT_SECRET: jphamisgod
      DATASOURCE_HOST: postgres
      DATASOURCE_PORT: 5432
      DATASOURCE_USERNAME: jpham
      DATASOURCE_PASSWORD: jpham005
      DATASOURCE_DATABASE: transcendence
    command: yarn start:dev
    
  pong-web:
    image: node:18-alpine
    ports:
      - "3001:3000"
    volumes:
      - ./web:/app
    working_dir: /app
    environment:
      API_SERVER_HOST: pong-server
    command: yarn start

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: jpham005
      POSTGRES_USER: jpham
      POSTGRES_DB: transcendence
    volumes:
      - ./server/init-postgres:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
