version: "3.4"

services:
  pong-server:
    image: node:18-alpine
    ports:
      - "${API_PORT}:3000"
      - "${WS_PORT}:3001"
    volumes:
      - ./server:/app
    working_dir: /app
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DATASOURCE_HOST: postgres
      DATASOURCE_PORT: ${POSTGRES_PORT}
      DATASOURCE_USERNAME: ${POSTGRES_USERNAME}
      DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      DATASOURCE_DATABASE: ${POSTGRES_DATABASE}
    command: yarn start:dev

  pong-web:
    image: node:18-alpine
    ports:
      - "${WEB_PORT}:5173"
    volumes:
      - ./web:/app
    working_dir: /app
    command: sh -c "yarn install ; yarn dev --host=0.0.0.0 --mode ${WEB_MODE}"

  postgres:
    image: postgres
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - ./server/init-postgres:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
